name: Docker Build And Push To Hub

on:
  push:
    branches:
    -master

jobs:
  build:
    runs -on: ubuntu-latest
    uses: actions/checkout@u3
    name: Login to Dockerhub
    name: Login to DockerHub
    uses: docker/login-action@v2
    with:
      username: ${{secrets.DOCKERHUB_USERNAME}}
      password: ${{secrets.DOCKERHUB_PASSWORD}}
    name: Build And Push
    uses: docker/build-push-action@v2
    with:
      context: .
      file: ./Dockerfile
      push: true
      tags: ${{secrets.DOCKERHUB_USERNAME}}/tallerfisol:latest
